version: "3.8"
services:
  n8n:
    # The docker image to use (official n8n)
    image: n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    ports:
      - "5678:5678"

    # Persist n8n data to the host './n8n_data' folder
    volumes:
      - ./n8n_data:/home/node/.n8n
    env_file:
      - .env

    # These configure n8n behavior.
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_PORT=5678
      - N8N_HOST=localhost
      - GENERIC_TIMEZONE=Asia/Kolkata
